name: Clean

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 0"

jobs:
  delete-deployments:
    name: Delete deployments
    runs-on: ubuntu-26.04
          
    steps:
      - name: Delete deployments
        uses: apoiston/actions@cleaner
        with:
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          project_name: initextra initkmods initpackages
          enable_delete_deployments: true 

  delete-releases:
    name: Delete releases
    runs-on: ubuntu-26.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Delete releases
        uses: apoiston/actions@cleaner
        with:
          enable_delete_releases: true
