name: Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-26.04

    steps:
      - name: Set timezone
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          date +"%Y-%m-%d %H:%M:%S %z"

      - name: Show runner info
        run: |
          date +"%Y-%m-%d %H:%M:%S %z"
          lscpu | grep -E '^Architecture|^CPU\(s\):|^Model name'
          uname -sr
          lsb_release -a
          free -h
          df -Th

      - name: Checkout
        uses: actions/checkout@v7

      - name: Build
        uses: apoiston/actions@builder
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          public_key: ${{ secrets.PUBLIC_KEY }}
          prepare_environment: ${{ secrets.PREPARE_ENVIRONMENT }}
          prepare_config: ${{ secrets.PREPARE_CONFIG }}
          export_image: ${{ secrets.EXPORT_IMAGE }}
          config_buildinfo: builder/config.buildinfo
          enable_build_toolchain: true
          enable_build_kernel: true
          enable_build_full: true
          enable_export_image: true

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: image
          path: |
            openwrt/builder/
            openwrt/builder-extra/
            openwrt/builder-kmods/
            openwrt/builder-packages/
